import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <h1 className="underline"> Hello World!</h1>
      </div>
    </>
  );
}
